olist_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      user: "{{ env_var('POSTGRES_USER', 'olist_admin') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'olist_secret_2024') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'olist_warehouse') }}"
      schema: public
      threads: 4
